# Generated by Django 3.0.5 on 2020-04-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='p_details',
        ),
    ]
