# Generated by Django 3.0.5 on 2020-04-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_auto_20200428_2224'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='pr_details',
        ),
    ]
